# Generated by Django 3.1 on 2020-08-26 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='answer',
        ),
        migrations.AddField(
            model_name='qa',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='QA.qa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
