# Generated by Django 3.1 on 2020-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_auto_20200826_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='active',
            new_name='published',
        ),
    ]
