# Generated by Django 3.1 on 2020-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_auto_20200826_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
