# Generated by Django 3.1 on 2020-08-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_qa_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='body',
            new_name='reply',
        ),
    ]
