# Generated by Django 3.1 on 2020-08-27 02:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QA', '0005_auto_20200827_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='replay',
            new_name='Reply',
        ),
    ]
