# Generated by Django 3.1 on 2020-08-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_auto_20200828_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='slug',
        ),
    ]
