# Generated by Django 3.1 on 2020-08-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qeustionsandswers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QA',
        ),
    ]
