# Generated by Django 3.0.1 on 2020-08-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qeustionsandswers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='answers',
            new_name='answer',
        ),
    ]
